/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V1IndexRouteImport } from './routes/v1/index'
import { Route as V1StatusRouteImport } from './routes/v1/status'
import { Route as V1ProvidersIndexRouteImport } from './routes/v1/providers/index'
import { Route as V1ModelsIndexRouteImport } from './routes/v1/models/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as V1SchemasProviderIndexRouteImport } from './routes/v1/schemas/$provider/index'
import { Route as V1ProvidersProviderModelsRouteImport } from './routes/v1/providers/$provider.models'
import { Route as V1ModelsProviderModelIdRouteImport } from './routes/v1/models/$provider.$modelId'
import { Route as V1AdminSyncProviderRouteImport } from './routes/v1/admin/sync.$provider'
import { Route as V1SchemasProviderActivityIndexRouteImport } from './routes/v1/schemas/$provider/$activity/index'
import { Route as V1SchemasProviderActivitySplatRouteImport } from './routes/v1/schemas/$provider/$activity/$'

const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1IndexRoute = V1IndexRouteImport.update({
  id: '/v1/',
  path: '/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StatusRoute = V1StatusRouteImport.update({
  id: '/v1/status',
  path: '/v1/status',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ProvidersIndexRoute = V1ProvidersIndexRouteImport.update({
  id: '/v1/providers/',
  path: '/v1/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ModelsIndexRoute = V1ModelsIndexRouteImport.update({
  id: '/v1/models/',
  path: '/v1/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SchemasProviderIndexRoute = V1SchemasProviderIndexRouteImport.update({
  id: '/v1/schemas/$provider/',
  path: '/v1/schemas/$provider/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ProvidersProviderModelsRoute =
  V1ProvidersProviderModelsRouteImport.update({
    id: '/v1/providers/$provider/models',
    path: '/v1/providers/$provider/models',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1ModelsProviderModelIdRoute = V1ModelsProviderModelIdRouteImport.update({
  id: '/v1/models/$provider/$modelId',
  path: '/v1/models/$provider/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminSyncProviderRoute = V1AdminSyncProviderRouteImport.update({
  id: '/v1/admin/sync/$provider',
  path: '/v1/admin/sync/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SchemasProviderActivityIndexRoute =
  V1SchemasProviderActivityIndexRouteImport.update({
    id: '/v1/schemas/$provider/$activity/',
    path: '/v1/schemas/$provider/$activity/',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1SchemasProviderActivitySplatRoute =
  V1SchemasProviderActivitySplatRouteImport.update({
    id: '/v1/schemas/$provider/$activity/$',
    path: '/v1/schemas/$provider/$activity/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/v1/status': typeof V1StatusRoute
  '/v1/': typeof V1IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/v1/models/': typeof V1ModelsIndexRoute
  '/v1/providers/': typeof V1ProvidersIndexRoute
  '/v1/admin/sync/$provider': typeof V1AdminSyncProviderRoute
  '/v1/models/$provider/$modelId': typeof V1ModelsProviderModelIdRoute
  '/v1/providers/$provider/models': typeof V1ProvidersProviderModelsRoute
  '/v1/schemas/$provider/': typeof V1SchemasProviderIndexRoute
  '/v1/schemas/$provider/$activity/$': typeof V1SchemasProviderActivitySplatRoute
  '/v1/schemas/$provider/$activity/': typeof V1SchemasProviderActivityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/v1/status': typeof V1StatusRoute
  '/v1': typeof V1IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/v1/models': typeof V1ModelsIndexRoute
  '/v1/providers': typeof V1ProvidersIndexRoute
  '/v1/admin/sync/$provider': typeof V1AdminSyncProviderRoute
  '/v1/models/$provider/$modelId': typeof V1ModelsProviderModelIdRoute
  '/v1/providers/$provider/models': typeof V1ProvidersProviderModelsRoute
  '/v1/schemas/$provider': typeof V1SchemasProviderIndexRoute
  '/v1/schemas/$provider/$activity/$': typeof V1SchemasProviderActivitySplatRoute
  '/v1/schemas/$provider/$activity': typeof V1SchemasProviderActivityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/v1/status': typeof V1StatusRoute
  '/v1/': typeof V1IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/v1/models/': typeof V1ModelsIndexRoute
  '/v1/providers/': typeof V1ProvidersIndexRoute
  '/v1/admin/sync/$provider': typeof V1AdminSyncProviderRoute
  '/v1/models/$provider/$modelId': typeof V1ModelsProviderModelIdRoute
  '/v1/providers/$provider/models': typeof V1ProvidersProviderModelsRoute
  '/v1/schemas/$provider/': typeof V1SchemasProviderIndexRoute
  '/v1/schemas/$provider/$activity/$': typeof V1SchemasProviderActivitySplatRoute
  '/v1/schemas/$provider/$activity/': typeof V1SchemasProviderActivityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/openapi.json'
    | '/v1/status'
    | '/v1/'
    | '/api/auth/$'
    | '/v1/models/'
    | '/v1/providers/'
    | '/v1/admin/sync/$provider'
    | '/v1/models/$provider/$modelId'
    | '/v1/providers/$provider/models'
    | '/v1/schemas/$provider/'
    | '/v1/schemas/$provider/$activity/$'
    | '/v1/schemas/$provider/$activity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/openapi.json'
    | '/v1/status'
    | '/v1'
    | '/api/auth/$'
    | '/v1/models'
    | '/v1/providers'
    | '/v1/admin/sync/$provider'
    | '/v1/models/$provider/$modelId'
    | '/v1/providers/$provider/models'
    | '/v1/schemas/$provider'
    | '/v1/schemas/$provider/$activity/$'
    | '/v1/schemas/$provider/$activity'
  id:
    | '__root__'
    | '/'
    | '/llms.txt'
    | '/openapi.json'
    | '/v1/status'
    | '/v1/'
    | '/api/auth/$'
    | '/v1/models/'
    | '/v1/providers/'
    | '/v1/admin/sync/$provider'
    | '/v1/models/$provider/$modelId'
    | '/v1/providers/$provider/models'
    | '/v1/schemas/$provider/'
    | '/v1/schemas/$provider/$activity/$'
    | '/v1/schemas/$provider/$activity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  V1StatusRoute: typeof V1StatusRoute
  V1IndexRoute: typeof V1IndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  V1ModelsIndexRoute: typeof V1ModelsIndexRoute
  V1ProvidersIndexRoute: typeof V1ProvidersIndexRoute
  V1AdminSyncProviderRoute: typeof V1AdminSyncProviderRoute
  V1ModelsProviderModelIdRoute: typeof V1ModelsProviderModelIdRoute
  V1ProvidersProviderModelsRoute: typeof V1ProvidersProviderModelsRoute
  V1SchemasProviderIndexRoute: typeof V1SchemasProviderIndexRoute
  V1SchemasProviderActivitySplatRoute: typeof V1SchemasProviderActivitySplatRoute
  V1SchemasProviderActivityIndexRoute: typeof V1SchemasProviderActivityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/': {
      id: '/v1/'
      path: '/v1'
      fullPath: '/v1/'
      preLoaderRoute: typeof V1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/status': {
      id: '/v1/status'
      path: '/v1/status'
      fullPath: '/v1/status'
      preLoaderRoute: typeof V1StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/providers/': {
      id: '/v1/providers/'
      path: '/v1/providers'
      fullPath: '/v1/providers/'
      preLoaderRoute: typeof V1ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/models/': {
      id: '/v1/models/'
      path: '/v1/models'
      fullPath: '/v1/models/'
      preLoaderRoute: typeof V1ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/schemas/$provider/': {
      id: '/v1/schemas/$provider/'
      path: '/v1/schemas/$provider'
      fullPath: '/v1/schemas/$provider/'
      preLoaderRoute: typeof V1SchemasProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/providers/$provider/models': {
      id: '/v1/providers/$provider/models'
      path: '/v1/providers/$provider/models'
      fullPath: '/v1/providers/$provider/models'
      preLoaderRoute: typeof V1ProvidersProviderModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/models/$provider/$modelId': {
      id: '/v1/models/$provider/$modelId'
      path: '/v1/models/$provider/$modelId'
      fullPath: '/v1/models/$provider/$modelId'
      preLoaderRoute: typeof V1ModelsProviderModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/sync/$provider': {
      id: '/v1/admin/sync/$provider'
      path: '/v1/admin/sync/$provider'
      fullPath: '/v1/admin/sync/$provider'
      preLoaderRoute: typeof V1AdminSyncProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/schemas/$provider/$activity/': {
      id: '/v1/schemas/$provider/$activity/'
      path: '/v1/schemas/$provider/$activity'
      fullPath: '/v1/schemas/$provider/$activity/'
      preLoaderRoute: typeof V1SchemasProviderActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/schemas/$provider/$activity/$': {
      id: '/v1/schemas/$provider/$activity/$'
      path: '/v1/schemas/$provider/$activity/$'
      fullPath: '/v1/schemas/$provider/$activity/$'
      preLoaderRoute: typeof V1SchemasProviderActivitySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  V1StatusRoute: V1StatusRoute,
  V1IndexRoute: V1IndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  V1ModelsIndexRoute: V1ModelsIndexRoute,
  V1ProvidersIndexRoute: V1ProvidersIndexRoute,
  V1AdminSyncProviderRoute: V1AdminSyncProviderRoute,
  V1ModelsProviderModelIdRoute: V1ModelsProviderModelIdRoute,
  V1ProvidersProviderModelsRoute: V1ProvidersProviderModelsRoute,
  V1SchemasProviderIndexRoute: V1SchemasProviderIndexRoute,
  V1SchemasProviderActivitySplatRoute: V1SchemasProviderActivitySplatRoute,
  V1SchemasProviderActivityIndexRoute: V1SchemasProviderActivityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
